#!/bin/bash

export STAT_PYTHON_CODE="$PWD/stat_python_code"

# execute all python scripts
for file in `ls -I "*.reference" $STAT_PYTHON_CODE`
    do
        python $STAT_PYTHON_CODE/$file > $STAT_PYTHON_CODE/$file".reference"
done
