#!/bin/bash

# set overrides for setlX launcher script
export OVERRIDE_setlXJarDirectory="$PWD/src/"

# other locations for tests
setlXlaunchScript="$PWD/src/setlX"

cd src

# clean the interpreter source
echo "=> Cleaning the setlX interpreter's source ..."
ant dist-clean

# build the binary version
echo "=> Rebuilding the setlX interpreter ..."
ant
if [ -f "$OVERRIDE_setlXJarDirectory/setlX.jar" ]
  then
    # clean it up again (does not remove the jar)
    ant clean
    echo "=> The setlX interpreter was build correctly."
else
    echo "=> Building the setlX interpreter failed ..."
    # break
    exit 1
fi

# ensure some files use Windows line-endings
if [ $(which unix2dos > /dev/null 2>&1; echo $?) -eq 0 ]
  then
    unix2dos setlX.cmd
fi

cd ../src_gfx

# clean the interpreter source
echo "=> Cleaning the setlX graphics library's source ..."
ant dist-clean

# build the binary version
echo "=> Rebuilding the setlX graphics library ..."
ant
if [ -e "$OVERRIDE_setlXJarDirectory/setlX-gfx.jar" ]
  then
    # clean it up again (does not remove the jar)
    ant clean
    echo "=> The setlX graphics library was build correctly."
else
    echo "=> Building the setlX graphics library failed ..."
    # break
    exit 1
fi

cd ..

# get version from executable (jar)
version=$("$setlXlaunchScript" --version)

# warn if current release is not tagged in git
gitWarning=""
if [ -d ".git" -a $(which git >/dev/null 2>&1; echo $?) -eq 0 ]
  then
    if [ $(git tag | grep -c "v$version") -ne 1 ]
      then
        gitWarning="WARNING: Version number of created distribution is not tagged in git!"
        version="$version.experimental"
    elif [ $(git diff --name-only "v$version" | wc -l) -gt 0 ]
      then
        gitWarning="WARNING: Source differs from commit tagged with 'v$version' in git!"
        version="$version.experimental"
    fi
fi

# create version string for file names
versionForFileNames=$(echo $version | tr "." "-")

# goto documentation source
cd documentation

# clean the documentation source
echo "=> Cleaning the documentation's source ..."
make dist-clean

# set version for documentation
echo "$version" > version.tex

# make documentation
echo "=> Rebuilding the documentation ..."
make
if [ -f developmentGuide.pdf -a -f manual.pdf ]
  then
    # move the finished PDFs where they belong
    mv -f *.pdf ../.
    # clean it up again
    make dist-clean
    echo "=> The documentation was build correctly."
else
    echo "=> Building the documentation failed ..."
    # break
    exit 1
fi

# goto pure grammar
cd ../grammar_pure

# clean the pure grammar source
echo "=> Cleaning the pure grammar source ..."
make clean
rm -rf Pure.g

# update the Pure.g grammar
echo "=> Updating the pure grammar"
make update
if [ -f Pure.g ]
  then
    # clean the pure grammar source (again)
    make clean
    echo "=> The pure grammar was updated correctly."
else
    echo "=> Update the pure grammar failed ..."
    # break
    exit 1
fi

# goto tutorial's source
cd ../Tutorial

# clean the documentation source
echo "=> Cleaning the tutorial's source ..."
make dist-clean

# make tutorial
echo "=> Rebuilding the tutorial ..."
make
if [ -f tutorial.pdf ]
  then
    # move the finished PDFs where they belong
    mv -f *.pdf ../.
    # clean it up again
    make dist-clean
    echo "=> The tutorial was build correctly."
else
    echo "=> Building the tutorial failed ..."
    # break
    exit 1
fi

# go to project root
cd ..

# create distribution names
binOnly="setlX_v$versionForFileNames.binary_only"
devel="setlX_v$versionForFileNames.devel"
examples="setlX_v$versionForFileNames.examples"

# remove distribution zips if present
rm -f "$binOnly.zip"
rm -f "$examples.zip"
rm -f "$devel.zip"
# remove other stuff
rm -f "diff.result"
rm -f diff.*.result

# create binary only zip
echo -n "=> Creating binary only distribution ... "
mkdir -p zipContents
cp changelog.txt manual.pdf tutorial.pdf src/setlX src/setlX.cmd src/setlX.jar src_gfx/setlX-gfx.jar zipContents/.
cp -r syntax_highlighting zipContents/.
cd zipContents; zip -qr "../$binOnly.zip" . ; cd ..
rm -rf zipContents
echo "done"

# create examples zip
echo -n "=> Creating example code distribution ... "
cp -r example_SetlX_code zipContents
while read -r -d $'\0' filename
  do
    rm -f "$filename"
done < <( find "zipContents" -type f ! -name "*.stlx" -print0 )
while read -r -d $'\0' emptyDir
  do
    rmdir "$emptyDir"
done < <( find "zipContents" -type d -empty -print0 )
cd zipContents; zip -qr "../$examples.zip" . ; cd ..
rm -rf zipContents
echo "done"

# remove the jars
cd src;ant dist-clean;cd ..
cd src_gfx;ant dist-clean;cd ..

# create development zip
echo -n "=> Creating development kit ... "
zip -qr "$devel.zip" . -x \*.zip \*.git\*
echo "done"

if [ -n "$gitWarning" ]
  then
    echo >&2
    echo "$gitWarning" >&2
    echo >&2
fi

