#!/bin/bash

tmpFile=$(mktemp -t setlx-XXXXXXXXXX)

manualTestFiles=""
skippedTestFiles=""
nSkipped=0

# set location for setlX launcher script
export OVERRIDE_setlXJarLocation="$PWD/src/setlX.jar"

# other locations for tests
setlXlaunchScript="$PWD/src/setlX"
diffDir="$PWD"

# prepare the interpreter
simpleTest=simpleTest/test.stlx
cd src; make test >/dev/null 2>"$tmpFile"; cd ..

# check for failed tests
failedCount=$(grep -c "failed" "$tmpFile")
everythingOkCount=$(grep -c "Everything is fine. Move along sir!" "$tmpFile")

# alert the user and stop
if [ $failedCount -gt 0 -o $everythingOkCount -ne 1 ]
  then
    echo "the initial testfile '$simpleTest' failed!"
    rm -f "$tmpFile"
    exit 1
else
    echo -e "executing file '$simpleTest' successful!\n"
fi

rm -f diff.*.result

# count number of files
count=0
while read -r -d $'\0' path
  do
    directoryname="$(dirname $path)"

    if [ "$1" == "no_performance" -a "$directoryname" == "example_SetlX_code/performance_test_code" ]
      then
        continue
    fi

    if [ ! -e "$path.reference" ]
      then
        continue
    fi

    count=$(bc <<< "$count + 1")

done < <( find -L example_SetlX_code -name "*.stlx" -print0 )

started=0
# loop through all SetlX files, execute them and compare to reference result
while read -r -d $'\0' path
  do
    shortname="${path#example_SetlX_code/}"
    directoryname="$(dirname $path)"
    filename="$(basename $path)"

    if [ "$1" == "no_performance" -a "$directoryname" == "example_SetlX_code/performance_test_code" ]
      then
        continue
    fi

    if [ ! -e "$path.reference" ]
      then
        manualTestFiles="$manualTestFiles$filename, "
        continue
    fi

    started=$(bc <<< "$started + 1")
    echo -n "($started/$count) executing file '$shortname' ..."

    # execute with setlX
    if [ -e "$path.input" ]
      then
        cd "$directoryname"; cat "$filename.input" | "$setlXlaunchScript" --predictableRandom "$filename" > "$tmpFile" 2>&1; cd - >/dev/null
    else
        cd "$directoryname"; "$setlXlaunchScript" --predictableRandom "$filename" > "$tmpFile" 2>&1; cd - >/dev/null
    fi

    diff "$path.reference" "$tmpFile" > "$diffDir/diff.result"
    if [ $? -eq 1 ]
      then

        skippedTestFiles="$skippedTestFiles$shortname, "
        nSkipped=$(bc <<< "$nSkipped + 1")

        mv "$diffDir/diff.result" "$diffDir/diff.$filename.result"
        echo -e " failed ... (see diff.$filename.result)\n"

    else
        echo -e " successful!\n"
    fi

done < <( find -L example_SetlX_code -name "*.stlx" -print0 )

rm -f "$diffDir/diff.result"

rm -f "$tmpFile"

manualTestFiles="${manualTestFiles%, }"
echo "The following examples need to be tested manually: $manualTestFiles"

if [ $nSkipped -gt 0 ]
  then
    skippedTestFiles="${skippedTestFiles%, }"
    echo
    echo "The following examples failed: $skippedTestFiles"
    echo
    echo "!! $nSkipped examples did fail this test !!"
fi

exit 0

