#!/bin/sh
#
#
# launcher script for the setlX interpreter on Unix-like systems
#
#

# insert full path to the setlX.jar file here
setlXJarLocation="setlX.jar"

############################## additional options ##############################
javaParameters=""

# execute with increased stack size
javaParameters="$javaParameters -Xss16m"

# uncomment to execute with increased memory size (6GB) (>2GB needs 64 Bit mode!)
#javaParameters="$javaParameters -Xms6g -Xmx6g"

# uncomment to force execution in 64 bit mode
#javaParameters="$javaParameters -d64"

# parameters for developing the interpreter
#javaParameters="$javaParameters -Xfuture"
#javaParameters="$javaParameters -Xprof"

################################################################################

if [ -f "$setlXJarLocation" ]
  then
    java -cp "$setlXJarLocation:$CLASSPATH" $javaParameters org.randoom.setlxUI.pc.SetlX "$@"
else
    echo "The setlX.jar file can not be found!"
fi

