#!/bin/sh

cd src

# clean the interpreter source
echo "=> Cleaning the setlX interpreter's source ..."
make dist-clean

# build the binary version
echo "=> Rebuilding the setlX interpreter ..."
make
if [ -f setlX.jar ]
  then
    # clean it up again (does not remove the jar)
    make clean
    echo "=> The setlX interpreter was build correctly."
else
    echo "=> Building the setlX interpreter failed ..."
    # break
    exit 1
fi

# get version from executable (jar)
version=$(./setlX --version)
versionForFileNames=$(echo $version | tr "." "-")

# goto documentation source
cd ../documentation

# clean the documentation source
echo "=> Cleaning the documentation's source ..."
make dist-clean

# set version for documentation
echo "$version" > version.tex

# make documentation
echo "=> Rebuilding the documentation ..."
make
if [ -f developmentGuide.pdf -a -f manual.pdf ]
  then
    # move the finished PDFs where they belong
    mv -f *.pdf ../.
    # clean it up again
    make dist-clean
    echo "=> The documentation was build correctly."
else
    echo "=> Building the documentation failed ..."
    # break
    exit 1
fi

# goto pure grammar
cd ../grammar_pure

# clean the pure grammar source
echo "=> Cleaning the pure grammar source ..."
make clean
rm -rf Pure.g

# update the Pure.g grammar
echo "=> Updating the pure grammar"
make update
if [ -f Pure.g ]
  then
    # clean the pure grammar source (again)
    make clean
    echo "=> The pure grammar was updated correctly."
else
    echo "=> Update the pure grammar failed ..."
    # break
    exit 1
fi

# go to project root
cd ..

# create distribution names
binOnly="setlX_v$versionForFileNames.binary_only"
source="setlX_v$versionForFileNames.source"
devel="setlX_v$versionForFileNames.devel"

# remove distribution zips if present
rm -f "$binOnly.zip"
rm -f "$source.zip"
rm -f "$devel.zip"
# remove other stuff
rm -f "diff.result"

# create binary only zip
echo -n "=> Creating binary only distribution ... "
mkdir -p zipContents
cp manual.pdf src/setlX src/win-setlX.cmd src/setlX.jar zipContents/.
cd zipContents; zip -qr "../$binOnly.zip" . ; cd ..
rm -rf zipContents
echo "done"

# remove the jar
cd src;make dist-clean;cd ..

# create development zip
echo -n "=> Creating development kit ... "
zip -qr "$devel.zip" . -x \*.zip
echo "done"
