#!/bin/sh

cd interpreter

# clean the interpreter source
make dist-clean

# build the binary version
echo "Rebuilding the setlX interpreter ..."
make jar
if [ -f setlX.jar ]
  then
    # clean it up again (does not remove the jar)
    make clean
    echo "The setlX interpreter was build correctly."
else
    echo "Building failed ..."
    # break
    exit 1
fi

# get version from executable (jar)
version=$(java -jar setlX.jar --version)
versionForFileNames=$(echo $version | tr "." "-")

# goto documentation source
cd ../documentation

# clean the documentation source
make dist-clean

# set version for documentation
echo "$version" > version.tex

# make documentation
make

# move the finished PDFs where they belong
mv *.pdf ../.

# clean the documentation source (again)
make dist-clean

# go to project root
cd ..

# create distribution names
binOnly="setlX_v$versionForFileNames.binary_only"
source="setlX_v$versionForFileNames.source"
devel="setlX_v$versionForFileNames.devel"

# remove distribution zips if present
rm -f "$binOnly.zip"
rm -f "$source.zip"
rm -f "$devel.zip"

# create binary only zip
echo -n "Creating binary only distribution ... "
zip -q "$binOnly.zip" manual.pdf interpreter/antlr/antlr_LICENSE.txt interpreter/setlX interpreter/setlX.jar interpreter/win-setlX.cmd
echo "done"

# remove the jar
cd interpreter;make -s dist-clean;cd ..

# create source zip
echo -n "Creating source distribution ... "
zip -qr "$source.zip" manual.pdf interpreter
echo "done"

# create development zip
echo -n "Creating development kit ... "
zip -qr "$devel.zip" . -x \*.zip
echo "done"
