#!/bin/bash

testFile=$(mktemp)

cd src;

./setlX --version > "$testFile"
if [ $? -ne 0 ]
  then
    cat "$testFile"

    rm -f "$testFile"
    exit 1
fi

resultFileName="../example_SetlX_code/performance_test_code/results/$(hostname | tr '.' '-')_v$(cat $testFile | tr '.' '-')"

resultFileNameReal="$resultFileName.real.csv"
resultFileNameUser="$resultFileName.user.csv"
resultFileNameSys="$resultFileName.sys.csv"

rm -f "$resultFileNameReal" "$resultFileNameUser" "$resultFileNameSys"

sumRealTime=0.0
sumUserTime=0.0
sumSysTime=0.0

# loop through all SetlX files, execute them and compare to reference result
while read -r -d $'\0' path
  do
    filename="${path#../example_SetlX_code/performance_test_code/}"

    echo "executing file '$filename' ..."

    execTime=$(
        time -p (
            # execute with setlX
            ./setlX --predictableRandom "$path" > "$testFile"
        ) 2>&1
    )

    diff "$path.reference" "$testFile" > /dev/null
    if [ $? -eq 1 ]
      then
        echo $execTime
        echo "executing file '$filename' failed!"

        rm -f "$testFile"
        exit 2
    else
        read -a timeArray <<<$execTime
        realTime=${timeArray[1]}
        userTime=${timeArray[3]}
        sysTime=${timeArray[5]}

        echo "$filename,$realTime" >> "$resultFileNameReal"
        echo "$filename,$userTime" >> "$resultFileNameUser"
        echo "$filename,$sysTime"  >> "$resultFileNameSys"

        echo "real: $realTime, user: $userTime, sys: $sysTime"

        sumRealTime=$(bc <<< "$sumRealTime + $realTime")
        sumUserTime=$(bc <<< "$sumUserTime + $userTime")
        sumSysTime=$(bc <<< "$sumSysTime + $sysTime")

        echo
    fi

done < <( find -L "../example_SetlX_code/performance_test_code" -name "*.stlx" -print0 )

cat "$resultFileNameReal" | sort > "$testFile"
echo "code example,time in seconds (real)" > "$resultFileNameReal"
cat "$testFile" >> "$resultFileNameReal"
echo "overall,$sumRealTime" >> "$resultFileNameReal"

cat "$resultFileNameUser" | sort > "$testFile"
echo "code example,time in seconds (user)" > "$resultFileNameUser"
cat "$testFile" >> "$resultFileNameUser"
echo "overall,$sumUserTime" >> "$resultFileNameUser"

cat "$resultFileNameSys" | sort > "$testFile"
echo "code example,time in seconds (sys)" > "$resultFileNameSys"
cat "$testFile" >> "$resultFileNameSys"
echo "overall,$sumSysTime" >> "$resultFileNameSys"

rm -f "$testFile"

echo "overall execution time:"
echo "real: $sumRealTime, user: $sumUserTime, sys: $sumSysTime"
echo

exit 0

