#!/bin/bash

tmpFile=$(mktemp)

manualTestFiles=""

# prepare the interpreter
simpleTest=simpleTest/test.stlx
cd src; ./setlX "$simpleTest" > $tmpFile 2>&1; cd ..

# check for failed tests
failedCount=$(grep -c "failed" $tmpFile)
okCount=$(grep -c "successful" $tmpFile)

# alert the user and stop
if [ $failedCount -gt 0 -o $okCount -lt 15 ]
  then
    echo "the initial testfile '$simpleTest' failed!"
    exit 1
else
    echo -e "executing file '$simpleTest' successful!\n"
fi

# loop through all SetlX files, execute them and compare to reference result
while IFS= read path
  do
    filename="${path#example_setlX_code/}"

    readCount=$(grep -c "read()" $path)
    getCount=$(grep -c "get()" $path)

    if [ $readCount -gt 0 -o $getCount -gt 0 -o ! -e $path.reference ]
      then
        manualTestFiles="$manualTestFiles$filename, "
        continue
    fi

    echo -n "executing file '$filename' ..."

    # execute with setlX
    cd src; ./setlX --predictableRandom ../$path > $tmpFile 2>&1; cd ..

    diff $path.reference $tmpFile > diff.result
    if [ $? -eq 1 ]
      then
        echo " failed ... (see diff.result)"
        break
    else
        echo -e " successful!\n"
    fi

done < <( find -L example_setlX_code -name "*.stlx" )

if [ ! -s diff.result ]
  then
    rm -f diff.result
fi

manualTestFiles="${manualTestFiles%, }"
echo "The following files need user input and must be tested manually: $manualTestFiles"

