#!/bin/sh

javaParameters=""

# uncomment to execute with increased stack size
#javaParameters="$javaParameters -Xss10m"

# uncomment to force execution in 64 bit mode
#javaParameters="$javaParameters -d64"

# parameters for developing the interpreter
#javaParameters="$javaParameters -Xfuture"
#javaParameters="$javaParameters -Xprof"

if [ -f bin/.buildSuccessful ]
  then
    java $javaParameters -cp bin:antlr/* SetlX $@
else
    if [ ! -f setlX.jar ]
      then
        if [ -d src ]
          then
            echo "Building the SetlX Interpreter ..."
            make -s jar
            if [ -f setlX.jar ]
              then
                make -s clean
                echo "The SetlX Interpreter was build correctly."
            else
                echo "Building failed ..."
            fi
        else
            echo "No source available -- the SetlX Interpreter can not be build."
        fi
    fi
    if [ -f setlX.jar ]
      then
        java $javaParameters -jar setlX.jar $@
    fi
fi
