#!/bin/sh

javaParameters=""

# uncomment to execute with increased stack size
#javaParameters="$javaParameters -Xss10m"

# uncomment to execute with increased maximum memory size (6GB) (>2GB needs 64 Bit mode!)
#javaParameters="$javaParameters -Xmx6g"

# uncomment to force execution in 64 bit mode
#javaParameters="$javaParameters -d64"

# parameters for developing the interpreter
#javaParameters="$javaParameters -Xfuture"
#javaParameters="$javaParameters -Xprof"

if [ -f bin/.buildSuccessful ]
  then
    java $javaParameters -cp bin:antlr/* SetlX "$@"
else
    if [ ! -f setlX.jar ]
      then
        if [ -d src ]
          then
            echo "=> Building the setlX interpreter ..."
            make jar
            if [ -f setlX.jar ]
              then
                make clean
                echo "=> The setlX interpreter was build correctly."
            else
                echo "=> Building failed ..."
            fi
        else
            echo "=> No source available -- the setlX interpreter can not be build."
        fi
    fi
    if [ -f setlX.jar ]
      then
        java $javaParameters -jar setlX.jar "$@"
    fi
fi

