#!/bin/sh
#
#
# totally UNSUPPORTED script for profiling the execution of the setlX interpreter
#
#

# insert full path to the setlX.jar file here
setlXJarLocation="setlX.jar"

# insert full path to library location here
setlXlibraryPath="$HOME/setlXlibrary/"

############################## additional options ##############################
javaParameters=""

# uncomment to force execution in 64 bit mode
#javaParameters="$javaParameters -d64"

# uncomment to execute with increased memory size (6GB) (>2GB needs 64 Bit mode!)
#javaParameters="$javaParameters -Xmx6144m"

# parameters for developing the interpreter
#javaParameters="$javaParameters -Xfuture"
#javaParameters="$javaParameters -Xprof"
javaParameters="$javaParameters -Xrunhprof:cpu=samples,depth=6,doe=y"

################################################################################

if [ -z "$SETLX_LIBRARY_PATH" ]
  then
    export SETLX_LIBRARY_PATH="$setlXlibraryPath"
fi

java_call="java"

if [ $(which rlwrap > /dev/null 2>&1; echo $?) -eq 0 ]
  then
    java_call="rlwrap -C $(basename $0) $java_call"
fi

if [ -f "$setlXJarLocation" ]
  then
    time (
        $java_call -cp "$setlXJarLocation:$CLASSPATH" $javaParameters org.randoom.setlxUI.pc.SetlX "$@"
        # strip out uninteresting stuff from profiling dump
        lnumber=$(grep -n 'CPU SAMPLES BEGIN' java.hprof.txt | awk -F: '{print $1}')
        tail -n +$lnumber java.hprof.txt
    )
else
    echo "The setlX.jar file can not be found!"
fi

