#!/bin/sh
#
#
# launcher script for the setlX interpreter on Unix-like systems
#
#

# insert full path to the setlX.jar file here
setlXJarLocation="setlX.jar"

############################## additional options ##############################
javaParameters=""

# uncomment to execute with increased memory size (6GB) (>2GB needs 64 Bit mode!)
#javaParameters="$javaParameters -Xms6g -Xmx6g"

# uncomment to force execution in 64 bit mode
#javaParameters="$javaParameters -d64"

# parameters for developing the interpreter
#javaParameters="$javaParameters -Xfuture"
#javaParameters="$javaParameters -Xprof"
#javaParameters="$javaParameters -Xrunhprof:cpu=samples,depth=6,doe=y"

################################################################################

if [ -n "$OVERRIDE_setlXJarLocation" ]
  then
    setlXJarLocation="$OVERRIDE_setlXJarLocation"
fi

java_call="java"

if [ $(which rlwrap > /dev/null 2>&1; echo $?) -eq 0 ]
  then
    java_call="rlwrap -C $(basename $0) $java_call"
fi

if [ -f "$setlXJarLocation" ]
  then
    $java_call -cp "$setlXJarLocation:$CLASSPATH" $javaParameters org.randoom.setlxUI.pc.SetlX "$@"
    exit $?
else
    echo "The setlX.jar file can not be found!"
    exit 1
fi

