(TeX-add-style-hook "basics"
 (lambda ()
    (LaTeX-add-labels
     "fig:setlx"
     "fig:sum.stlx"
     "fig:sum-recursive.stlx"
     "fig:simple.stlx"
     "fig:primes-sieve.stlx"
     "fig:primes-slim.stl"
     "fig:function.stl"
     "fig:buggy-function.stl"
     "fig:primes-tuple.stl"
     "fig:sort.stl"
     "fig:from.stlx"
     "fig:simple-tuple.stlx"
     "fig:min-sort.stl"
     "fig:if"
     "fig:primes-forall.stlx"
     "fig:case"
     "fig:case.stlx"
     "fig:while"
     "fig:prime-proc"
     "fig:for"
     "fig:primes-for.stlx"
     "fig:primes-eratosthenes.stlx"
     "fig:solve.stlx"
     "fig:poker-triple.stlx"
     "fixpunkt"
     "fig:transitive-closure.stlx"
     "path.stlx"
     "fig:path-cyclic.stlx"
     "fig:find-path"
     "fig:wolf-ziege"
     "fig:wolf-ziege-solution")))

